stages:
  - Code Scanning
  - building 
  - Container Security
  - pushing

#Code Scanning contain 3 jobs that can be executed at the same time , these jobs are : Secret scanning , Code Quality , SAST .
#Container Security contains 2 jobs : container scanning , image signing .


variables:
  DOCKER_IMAGE_TAG: DevSecOps-uploaded-repo:${CI_COMMIT_REF_SLUG}


before_script:
  - echo "Starting Pipeline for Project"

#Before running the Scans , we have to make sure that docker is running on our runner machine , ( mazal maderthach )
Secret Scanning: 
  stage: Code Scanning
  script:
    - >
      docker run --rm -v $CI_PROJECT_DIR:/data trufflesecurity/trufflehog:latest trufflehog /data --json --max_depth=5 > trufflehog_report.json
    - >
      if [ -s trufflehog_report.json ]; then
        echo "WARNING: Secrets detected. Review trufflehog_report.json for details."
        cat trufflehog_report.json
      else
        echo "No secrets detected."
      fi
  artifacts:
    when: always
    paths:
      - trufflehog_report.json
  only:
    - branches


Code Quality: 
  stage: Code Scanning
#Code Scanning is still not finished

build:
  stage: building
  script:
    - docker build -t $CI_REGISTRY/$DOCKER_IMAGE_TAG .
  only:
    - branches

Image Scanning:
  stage: Container Security
  script:
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --format json --output trivy_report.json --no-fail $CI_REGISTRY/$DOCKER_IMAGE_TAG
    - echo "Trivy vulnerability scan completed. Check trivy_report.json for details."
  artifacts:
    when: always
    paths:
      - trivy_report.json
  only:
    - branches


signing & pushing: 
  stage: pushing
  script:
    - export DOCKER_CONTENT_TRUST=1
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="your_passphrase_here"
    #idealement had l passphrase khassha tkon stored as a protected variable f gitlab settings 
    - docker push $CI_REGISTRY/$DOCKER_IMAGE_TAG
  only:
    - master

    