stages:
  - pre_scan
  - Code Scanning
  - building 
  - image Security
  - pushing
  - container security
  - launch_sidecar
  - scan_container
  - nikto
  - owasp_zap

variables:
  DOCKER_IMAGE_TAG: DevSecOps-uploaded-repo:${CI_COMMIT_REF_SLUG}
  DOCKER_IMAGE: "Registry IP Location For Project Images"
  TOOLS_IMAGE: "Registry IP Location For Tools Images"
  SONAR_KEY: ""

check_docker:
  stage: pre_scan
  script:
    - docker info || (echo "Docker is not running or not installed"; exit 1)
  tags:
    - docker-local

lint:
  stage: Code Scanning
  image: "docker.io/hadolint/hadolint:v1.18.0"
  script:
    - hadolint Dockerfile > hadolint-results.txt
  artifacts:
    paths:
      - hadolint-results.txt
    expose_as: 'Hadolint Results'
  tags:
    - docker-local

Secret Scanning: 
  stage: Code Scanning
  script:
    - >
      docker run --rm -v $CI_PROJECT_DIR:/data trufflesecurity/trufflehog:latest trufflehog /data --json --max_depth=5 > trufflehog_report.json
    - >
      if [ -s trufflehog_report.json ]; then
        echo "WARNING: Secrets detected. Review trufflehog_report.json for details."
        cat trufflehog_report.json
      else
        echo "No secrets detected."
      fi
  artifacts:
    when: always
    paths:
      - trufflehog_report.json
    expose_as: 'Trufflehog Results'
  only:
    - branches
  tags:
    - docker-local


build_image:
  stage: building
  script:
    - |
      tag=$(git tag --contains ${CI_COMMIT_SHA} | awk '{print $1}')
      if [[ -z "$tag" ]]; then
        tag="${CI_COMMIT_REF_NAME}"
        if [[ "${CI_COMMIT_REF_NAME}" == "master" ]]; then
          tag="latest"
        fi
      fi
      docker build -t "${DOCKER_IMAGE}:${tag}" .

Image Scanning:
  stage: image Security
  script:
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --format json --output trivy_report.json --no-fail $CI_REGISTRY/$DOCKER_IMAGE_TAG
    - echo "Trivy vulnerability scan completed. Check trivy_report.json for details."
  artifacts:
    when: always
    paths:
      - trivy_report.json
  only:
    - branches

signing & pushing:
  stage: pushing
  script:
    - export DOCKER_CONTENT_TRUST=1
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="your_passphrase_here"
    - docker push $CI_REGISTRY/$DOCKER_IMAGE_TAG
  only:
    - master

launch_sidecar:
  stage: container security
  script:
    - docker run --detach --network lab --name ${CI_JOB_NAME}-${CI_PIPELINE_ID} --rm ${DOCKER_IMAGE}:${tag}

scan_container:
  stage: container security
  image: ${TOOLS_IMAGE}
  script:
    - anchore-cli system status
    - anchore-cli image add ${DOCKER_IMAGE}:${tag}
    - anchore-cli image wait ${DOCKER_IMAGE}:${tag}
    - anchore-cli image vuln ${DOCKER_IMAGE}:${tag} all | tee anchore-results.txt
    - anchore-cli evaluate check ${DOCKER_IMAGE}:${tag} --detail >> anchore-results.txt

nikto:
  stage: container security
  image: ${TOOLS_IMAGE}
  script:
    - mkdir -p reports
    - curl --max-time 120 --retry 60 --retry-connrefused --retry-delay 5 --fail --silent http://${CI_JOB_NAME}-${CI_PIPELINE_ID}:3000 || exit 1
    - nikto.pl -ask no -nointeractive -output reports/nikto.html -Plugins '@@ALL;-sitefiles' -Tuning x7 -host http://${CI_JOB_NAME}-${CI_PIPELINE_ID}:3000 > nikto-results.txt

owasp_zap:
  stage: container security
  image: "owasp/zap2docker-weekly"
  script:
    - mkdir -p reports
    - curl --max-time 120 --retry 60 --retry-connrefused --retry-delay 5 --fail --silent http://${CI_JOB_NAME}-${CI_PIPELINE_ID}:3000 || exit 1
    - zap-baseline.py -m 5 -T 5 -I -r reports/zapreport.html -t "http://${CI_JOB_NAME}-${CI_PIPELINE_ID}:3000"

after_script:
  - find . -type f -name '*-results.txt' -exec mv {} reports/ \;
